# Generated by Django 5.1.7 on 2025-04-02 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prospects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('montant_estime', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('new', 'Nouveau'), ('in_progress', 'En cours'), ('won', 'Gagné'), ('lost', 'Perdu')], default='new', max_length=20)),
                ('date_cloture', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='prospects.prospect')),
            ],
        ),
    ]
